name: Al_Kitab
description: An offline quran app.

publish_to: 'none' 

version: 1.0.1+9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  clipboard: ^0.1.3
  scoped_model: ^2.0.0
  share: ^2.0.4
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.1.6 
  http: ^0.13.5
  provider: ^6.0.5
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - json/
  - json/surah/
  - json/sajda/
  - assets/icons/

  fonts:
    - family: PBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: PLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: PRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: PMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: RSR
      fonts:
        - asset: assets/fonts/RougeScript-Regular.ttf
        
        
  
